# Generated by Django 4.0.4 on 2022-05-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthUnityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo de Unidade Básica de Saúde',
                'verbose_name_plural': 'Arquivos de Unidades Básicas de Saúde',
            },
        ),
        migrations.CreateModel(
            name='HealthUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes_code', models.PositiveIntegerField()),
                ('ibge_uf', models.PositiveIntegerField()),
                ('ibge_city', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=253)),
                ('address', models.CharField(max_length=253)),
                ('district', models.CharField(blank=True, max_length=253, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.healthunityfile')),
            ],
            options={
                'verbose_name': 'Unidade de Saúde',
                'verbose_name_plural': 'Unidades de Saúde',
            },
        ),
    ]
